Repository leanix/leanix-github-agent, pull requests merged in 2024-12, with the labels that each got.

#57 CID-2940 Use 5 max attempts for retrying establishing connection
  config/detekt/detekt.yml
  src/main/kotlin/net/leanix/githubagent/config/WebSocketClientConfig.kt
  src/main/kotlin/net/leanix/githubagent/services/CachingService.kt
  src/main/resources/application.yaml
  src/test/kotlin/net/leanix/githubagent/config/WebSocketClientConfigTests.kt
Labels: chore

#64 cid-3370: Add call to send org when a new installation happens
  src/main/kotlin/net/leanix/githubagent/services/GitHubScanningService.kt
  src/main/kotlin/net/leanix/githubagent/services/WebhookEventService.kt
  src/test/kotlin/net/leanix/githubagent/services/WebhookEventServiceTest.kt
Labels: bug

#66 cid-3383: Enable async
  src/main/kotlin/net/leanix/githubagent/config/AsyncConfig.kt
Labels: bug

#67 cid-3388: Fix agent version to 0.0.3
  build.gradle.kts
Labels: patch
